"""add_role_and_created_by_fields

Revision ID: 69bb4dce5c44
Revises: de8444b2b72b
Create Date: 2026-01-21 09:21:41.750046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69bb4dce5c44'
down_revision: Union[str, None] = 'de8444b2b72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_by_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=10), nullable=True, server_default='STAFF'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # Update existing users to ADMIN role
    op.execute("UPDATE users SET role = 'ADMIN' WHERE role IS NULL")
    op.execute("UPDATE orders SET created_by_name = 'Admin User' WHERE created_by_name IS NULL OR created_by_name = ''")
    # Make fields non-nullable after populating
    op.alter_column('users', 'role', nullable=False)
    op.alter_column('orders', 'created_by_name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('orders', 'created_by_name')
    # ### end Alembic commands ###
