"""Add customer_address to orders table

Revision ID: 6cb08e3e02bd
Revises: f50c278895e0
Create Date: 2026-04-06 14:04:56.189395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb08e3e02bd'
down_revision: Union[str, None] = 'f50c278895e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_assets_album_id', 'media_assets', type_='foreignkey')
    op.create_foreign_key(None, 'media_assets', 'albums', ['album_id'], ['id'])
    op.add_column('orders', sa.Column('customer_address', sa.String(500), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_address')
    op.drop_constraint(None, 'media_assets', type_='foreignkey')
    op.create_foreign_key('fk_media_assets_album_id', 'media_assets', 'albums', ['album_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
