"""Create quotations table

Revision ID: a1b2c3d4e5f6
Revises: fec3103de63a
Create Date: 2026-04-09 04:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'fec3103de63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by_name', sa.String(length=255), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_address', sa.String(length=500), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('manual_items', sa.JSON(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_payment', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_date', sa.String(length=50), nullable=True),
    sa.Column('valid_until', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_created_at'), 'quotation', ['created_at'], unique=False)
    op.create_index(op.f('ix_quotation_status'), 'quotation', ['status'], unique=False)
    op.create_index(op.f('ix_quotation_user_id'), 'quotation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_user_id'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_status'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_created_at'), table_name='quotation')
    op.drop_table('quotation')
    # ### end Alembic commands ###
