"""add_cloudinary_public_id_to_items_and_media_assets

Revision ID: de8444b2b72b
Revises: 26aafd951229
Create Date: 2026-01-21 00:33:42.620176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8444b2b72b'
down_revision: Union[str, None] = '26aafd951229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
    op.add_column('media_assets', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.drop_column('media_assets', 'cloudinary_public_id')
    op.drop_column('items', 'cloudinary_public_id')
    # ### end Alembic commands ###
