"""Add manual_items column to orders table

Revision ID: fec3103de63a
Revises: 7cfa8f197509
Create Date: 2026-04-07 12:25:38.502155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec3103de63a'
down_revision: Union[str, None] = '7cfa8f197509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('manual_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'manual_items')
    # ### end Alembic commands ###
